version: "3"

services:
  database:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bus_management
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d  # Mount the directory containing SQL scripts
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "log_statement=all"]
